### ISSUE TITLE
Need to test with SELinux

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/ansible-role-repox#1]
I suspect that this would blow up with SELinux enforcement

**Comment by jsnshrmn** [comment]
Basically you will at least need to set a tomcat appropriate default context for the war, and then do a restorecon before letting tomcat autodeploy.  See an apache example here:
https://github.com/OULibraries/ansible-role-d7/blob/master/files/d7_perms.sh#L55

**Comment by calcnerd256** [comment]
https://github.com/calcnerd256/ansible-role-repox/commit/046821503610ee3057a70ceaac857d25307e032c
