### ISSUE TITLE
Deploy repox to / instead of /repox

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/ansible-role-repox#5]
Right now repox is served out of /repox.
That doesn't have to be the case.
You can write app-specific xml config for tomcat that can let you replace ROOT without actually overwriting the root app.

**Comment by calcnerd256** [comment]
https://benhutchison.wordpress.com/2008/07/30/how-to-configure-tomcat-root-context/

**Comment by calcnerd256** [comment]
https://github.com/calcnerd256/ansible-role-repox/commit/9f76fcf3ee8e9578356cd3b838a59e001f2612b5

**Comment by calcnerd256** [comment]
https://github.com/OULibraries/ansible-role-repox/pull/6
